on:
  push:
  workflow_dispatch:

name: Deploy website on push

jobs:
  web-deploy:
    name: Deploy frankzinsli.ch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: Set Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install yarn & build
        run: |
          yarn install
          yarn build

      - name: Upload files via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          local-dir: ./dist/
          server-dir: /httpdocs
          dangerous-clean-slate: true
